#!/bin/sh
ALL="$(echo "$@" | xargs cat | tr ' /' '\n.')"

if [ -n "$ALL" ]; then
echo "$ALL" | sed 's/^\(.*\)$/extern const char _binary_\1_start[];\nextern const char _binary_\1_end[];/g' | tr '.' '_'
fi

cat << 'EOF'

struct mem_file _myfiles[] = {
EOF

if [ -n "$ALL" ]; then
echo "$ALL" | sed 's/^\(.*\)\.lua$/  {"\1",\n   _binary_\1_lua_start, _binary_\1_lua_end },/g' |
    sed 'n; s/\./_/g'
fi

cat << 'EOF'
  { NULL, NULL, NULL }
};
EOF
