TOPDIR = ../..
PROG = build.o
CXXSRCS = lua.cc
CSRCS = lutf8lib-compat.c lauxlib-compat.c

LDFLAGS = -r -nostdlib

include ${TOPDIR}/make/comm.mk
include ${TOPDIR}/make/c.mk
include ${TOPDIR}/make/cxx.mk
include ${TOPDIR}/user.mk
