TOPDIR = ..
PROG = driver
CSRCS = main.c
OBJS += ${TOPDIR}/lua-nk/nk.a

LDFLAGS = ${LUA_LDFLAGS} ${XFT_LDFLAGS}

include ${TOPDIR}/make/comm.mk
include ${TOPDIR}/make/c.mk
include ${TOPDIR}/make/cxx.mk
include ${TOPDIR}/user.mk
